config/routes.rb
Rails.application.routes.draw do

  mount Depot::API => '/api'

  devise_for :users, controllers: { sessions: "users_session" }
  resources :products do
    resources :uploads
  end

  root 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :uploads
  accepts_nested_attributes_for :uploads, reject_if: :all_blank
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :product
  has_attached_file :upload, styles: { medium: "300x300>", thumb: "100x100>" },
                             path: ":rails_root/public/system/:class/:style/:filename",
                             url: "/system/:class/:style/:filename"
  validates_attachment_content_type :upload, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum role: [:admin, :moderator, :user]
  devise :database_authenticatable, :registerable,
         #:recoverable, :trackable 
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  layout :layout_by_resource
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end

  def layout_by_resource
    if devise_controller?
      "login_layout"
    else
      "application"
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  skip_load_resource only: [:create]
  respond_to :html
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = @products.includes(:uploads).page(params[:page])
  end

  def show

  end

  def new
    @product.uploads.build
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    redirect_to @product if @product.save
  end

  def update
    @product.update(product_params)
    render :show
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :price, { uploads_attributes: [:upload] } )
    end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  load_and_authorize_resource
  respond_to :html

  before_action :set_upload, only: [:show, :edit, :update, :destroy]
  
  def index

  end

  def show

  end

  def new
    @upload = Upload.new
  end

  def edit

  end

  def create
    @upload.save
  end

  def update
    @upload.update(upload_params)
  end

  def destroy
    @upload.destroy
  end

  private
    def set_upload
      @product = Upload.find(params[:id])
    end

    def upload_params
      params.require(:upload).permit(:upload)
    end
end

app/controllers/users_session_controller.rb
class UsersSessionController < Devise::RegistrationsController
  respond_to :js, only: :create

  def create
    resource = warden.authenticate!(scope: resource_name, recall: "#{controller_path}#failure")
    sign_in_and_redirect(resource_name, resource)
  end
 
  def sign_in_and_redirect(resource_or_scope, resource=nil)
    scope = Devise::Mapping.find_scope!(resource_or_scope)
    resource ||= resource_or_scope
    sign_in(scope, resource) unless warden.user(scope) == resource
    return render json: {success: true}
  end
 
  def failure
    return render json: {success: false, errors: ["Login failed."]}
  end
end  

app/helpers/application_helper.rb
module ApplicationHelper
  ALERT_TYPES = [:error, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type.to_s == :notice.to_s
      type = :error if type.to_s == :alert.to_s
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def login_form
    if user_signed_in? 
      render 'users/sessions/authentificated'
    else
      render 'users/sessions/new'
    end    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.slim
h1 Hello world

app/views/layouts/_navbar.html.slim
= nav_bar static: :top, brand: "New depot", responsive: true do
  = menu_group do
    = menu_item "Home", root_path
    = menu_divider
    = menu_item "Products", products_path

app/views/layouts/_sign_in.html.slim
= login_form

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "NewDepot"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
  body
    = render 'layouts/navbar'
    .container-fluid
      .row
        .col-md-2
          .well.sidebar-nav
            ul.nav.nav-list.sign_in
              li.nav-header Login area
              = render 'layouts/sign_in'
        .col-md-10
          = bootstrap_flash
          = yield

      footer
        p &copy; Company 2014
    = javascript_include_tag "application"

app/views/layouts/login_layout.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "NewDepot"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  body
    .navbar.navbar-fluid-top
      .navbar-inner
        .container-fluid
          a.btn.btn-navbar data-target=".nav-collapse" data-toggle="collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.brand href="/"NewDepot
          .container-fluid.nav-collapse
            ul.nav
              li= link_to "Products", products_path
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"
    .container-fluid
      .row-fluid
        .span8.offset4
          = bootstrap_flash
          = yield             
  footer
    p &copy; Company 2013 
  = javascript_include_tag "application"

app/views/products/_form.html.slim
= simple_form_for @product, :html => { :class => "form-horizontal",  mutlipart: true } do |f|
  = f.input :title
  = f.input :description
  = f.input :price
  .file_upload_area
    = f.simple_fields_for :uploads do |ff|
      .file_upload
        = ff.input :upload, as: :upload
        = image_tag ''
  span.add_field Add field  
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), products_path, :class => 'btn'

app/views/products/edit.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/index.html.slim
/ - model_class = Product
/ div class="page-header"
/   h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
/   = paginate @products
/ table class="table table-striped"
/   thead
/     tr
/       th= model_class.human_attribute_name(:id)
/       th= model_class.human_attribute_name(:uploads)
/       th= model_class.human_attribute_name(:title)
/       th= model_class.human_attribute_name(:description)
/       th= model_class.human_attribute_name(:price)
/       th= model_class.human_attribute_name(:created_at)
/       th=t '.actions', :default => t("helpers.actions")
/   tbody
/     - @products.each do |product|
/       tr
/         td= link_to product.id, product_path(product)
/         td= image_tag product.uploads.first.upload.url
/         td= product.title
/         td= product.description
/         td= product.price
/         td=l product.created_at
/         td
/           = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(product), :class => 'btn btn-mini'
/           '
/           = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

/ = link_to t('.new', :default => t("helpers.links.new")), new_product_path, :class => 'btn btn-primary'

div ng-app="new_depot.app.products" ng-controller="ProductsCtrl"
  table.table ng-table="tableParams"
    colgroup
      col.col-lg-2
      col.col-lg-4
      col.col-lg-2
    tr ng-repeat="product in $data"
      td data-title="'Image'"
        img ng-src="{{product.uploads[0].upload}}"
      td data-title="'Title'" {{product.title}}
      td data-title="'Created at'" {{product.created_at}}

app/views/products/new.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/products/show.html.slim
- model_class = Product
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:title) + ':'
  br
  = @product.title
p
  strong= model_class.human_attribute_name(:description) + ':'
  br
  = @product.description
p
  strong= model_class.human_attribute_name(:price) + ':'
  br
  = @product.price

- @product.uploads.each do |upload|
  p
    =image_tag upload.upload.url

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), products_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_product_path(@product), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/uploads/_script.html.erb
<script>
    var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
    };
  </script>

  <!-- The template to display files available for upload -->
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
      <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
      <td>
        <div class="progress progress-success progress-striped active"><div class="bar progress-bar" style="width:0%;"></div></div>
      </td>
      <td class="start" style="display:none">{% if (!o.options.autoUpload) { %}
        <button class="btn btn-primary">
          <i class="icon-upload icon-white"></i>
          <span>{%=locale.fileupload.start%}</span>
        </button>
        {% } %}</td>
      {% } else { %}
      <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning" onclick="minus()">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
        {% } %}</td>
    </tr>
    {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
    
  </script>

  <script type="text/javascript" charset="utf-8">
    var num_added = 0;
    var added = 0;
    var all_data = {};
    function minus() {
      num_added--;
    };
    function submit() {
      if (num_added == 0) {
        document.forms["fileupload"].submit();
      }
      
    };
    $(function () {

        $('#startbutton').click(function() {
          if (num_added == 0) {
            document.forms["fileupload"].submit();
          }

        });

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
          complete: function (e, data) {
            window.location = "<%= root_url %>";
        },
          singleFileUploads: false
        })  .bind('fileuploadadd', function (e, data) {num_added++;})
            .bind('fileuploadsubmit', function (e, data) {
             if(added < num_added)
                  {
                  if (added == 0)
                      all_data = data;
                  else
                      {
                      $.each(data['files'], function(i, file){
                      all_data['files'].push(file);
                      });
                      $.each(data['context'], function(i, context){
                      all_data['context'].push(context);
                      });
                      }
                  added++;
                  if (added == num_added)
                      {
                      added++;
                      all_data.submit();
                      }
                  return false;
              }
            })
            .bind('fileuploadsend', function (e, data) {num_added = 0; added = 0;});
            
        // 
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimpFileupload'), 
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          console.log(files);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));
          // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
  </script>

app/views/uploads/index.html.slim
div.container
  h2 Upload file
  = form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f|
    /! The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload
    div.row.fileupload-buttonbar
      div.span7
        /<!-- The fileinput-button span is used to style the file input field as button -->
        span.btn.btn-success.fileinput-button
          i.icon-plus.icon-white
          span Add files...
          = f.file_field :upload
        button.btn.btn-primary.start type="submit"
          i.icon-upload.icon-white
          span Start upload
        button.btn.btn-warning.cancel type="reset"
          i.icon-ban-circle.icon-white
          span Cancel upload
        button.btn.btn-danger.delete type="button"
          i.icon-trash.icon-white
          span Delete
        input.toggle type="checkbox"
      div.span5
        /<!-- The global progress bar -->
        div.progress.progress-success.progress-striped.active.fade
          div.bar style="width:0%;"
    /<!-- The loading indicator is shown during image processing -->
    div.fileupload-loading
    br
    /<!-- The table listing the files available for upload/download -->
    table.table.table-striped
      tbody.files data-toggle="modal-gallery" data-target="#modal-gallery"

= render 'script'